function [fitresult, gof] = createFit(hx, hy)
%CREATEFIT(HX,HY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : hx
%      Y Output: hy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Nov-2014 12:34:27


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( hx, hy );

% Set up fittype and options.
ft = fittype( 'gauss5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 13 0 -Inf 25 0 -Inf 0 0 -Inf 29 0 -Inf 17 0];
opts.StartPoint = [2094.62137561779 15 1.07777819024508 1526.81538398324 27 1.5507012928391 1510.8503649283 5 1.33927019868881 1404.04505202755 29.5 1.63888555287678 1324.75289401546 21 2.21288204596853];
opts.Upper = [Inf 17 Inf Inf 29 Inf Inf 10 Inf Inf 32 Inf Inf 23 Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'hy vs. hx', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
%xlabel( 'hx' );
%ylabel( 'hy' );
%grid on
