# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame_range_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(408, 297)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.okBtn = QtWidgets.QPushButton(Dialog)
        self.okBtn.setObjectName("okBtn")
        self.gridLayout.addWidget(self.okBtn, 9, 1, 1, 1)
        self.ef_spinBox_488 = QtWidgets.QSpinBox(Dialog)
        self.ef_spinBox_488.setObjectName("ef_spinBox_488")
        self.ef_spinBox_488.setMaximum(10000000)
        self.gridLayout.addWidget(self.ef_spinBox_488, 7, 3, 1, 1)
        self.ef_spinBox_561 = QtWidgets.QSpinBox(Dialog)
        self.ef_spinBox_561.setObjectName("ef_spinBox_561")
        self.ef_spinBox_561.setMaximum(10000000)
        self.gridLayout.addWidget(self.ef_spinBox_561, 5, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{color: \'cyan\'}")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 2, 1, 1)
        self.sf_spinBox_488 = QtWidgets.QSpinBox(Dialog)
        self.sf_spinBox_488.setObjectName("sf_spinBox_488")
        self.sf_spinBox_488.setMaximum(10000000)
        self.gridLayout.addWidget(self.sf_spinBox_488, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{color: rgb(255, 0, 0)}")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.sf_spinBox_750 = QtWidgets.QSpinBox(Dialog)
        self.sf_spinBox_750.setObjectName("sf_spinBox_750")
        self.sf_spinBox_750.setMaximum(10000000)
        self.gridLayout.addWidget(self.sf_spinBox_750, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.ef_spinBox_750 = QtWidgets.QSpinBox(Dialog)
        self.ef_spinBox_750.setObjectName("ef_spinBox_750")
        self.ef_spinBox_750.setMaximum(10000000)
        self.gridLayout.addWidget(self.ef_spinBox_750, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel{color: rgb(255, 255, 0)}")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.ef_spinBox_647 = QtWidgets.QSpinBox(Dialog)
        self.ef_spinBox_647.setObjectName("ef_spinBox_647")
        self.ef_spinBox_647.setMaximum(10000000)
        self.gridLayout.addWidget(self.ef_spinBox_647, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.sf_spinBox_561 = QtWidgets.QSpinBox(Dialog)
        self.sf_spinBox_561.setObjectName("sf_spinBox_561")
        self.sf_spinBox_561.setMaximum(10000000)
        self.gridLayout.addWidget(self.sf_spinBox_561, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel{color: rgb(255,85, 0)}")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.sf_spinBox_647 = QtWidgets.QSpinBox(Dialog)
        self.sf_spinBox_647.setObjectName("sf_spinBox_647")
        self.sf_spinBox_647.setMaximum(10000000)
        self.gridLayout.addWidget(self.sf_spinBox_647, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 1, 1, 1)
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        self.cancelBtn.setObjectName("cancelBtn")
        self.gridLayout.addWidget(self.cancelBtn, 9, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Frame Range"))
        self.okBtn.setText(_translate("Dialog", "OK"))
        self.label_12.setText(_translate("Dialog", "488"))
        self.label_5.setText(_translate("Dialog", "Start Frame"))
        self.label_6.setText(_translate("Dialog", "End Frame"))
        self.label_9.setText(_translate("Dialog", "750"))
        self.label_3.setText(_translate("Dialog", "End Frame"))
        self.label.setText(_translate("Dialog", "Start Frame"))
        self.label_11.setText(_translate("Dialog", "561"))
        self.label_7.setText(_translate("Dialog", "Start Frame"))
        self.label_2.setText(_translate("Dialog", "Start Frame"))
        self.label_8.setText(_translate("Dialog", "End Frame"))
        self.label_4.setText(_translate("Dialog", "End Frame"))
        self.label_10.setText(_translate("Dialog", "647"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

