# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 650))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.load_layout = QtWidgets.QGridLayout()
        self.load_layout.setObjectName("load_layout")
        self.exp_lbl = QtWidgets.QLabel(self.centralwidget)
        self.exp_lbl.setMinimumSize(QtCore.QSize(300, 25))
        self.exp_lbl.setMaximumSize(QtCore.QSize(300, 16777215))
        self.exp_lbl.setBaseSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exp_lbl.setFont(font)
        self.exp_lbl.setObjectName("exp_lbl")
        self.load_layout.addWidget(self.exp_lbl, 1, 0, 1, 1)
        self.load_exp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_exp_btn.setMinimumSize(QtCore.QSize(150, 25))
        self.load_exp_btn.setMaximumSize(QtCore.QSize(150, 25))
        self.load_exp_btn.setBaseSize(QtCore.QSize(25, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_exp_btn.setFont(font)
        self.load_exp_btn.setObjectName("load_exp_btn")
        self.load_layout.addWidget(self.load_exp_btn, 0, 0, 1, 1)
        self.load_mov_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_mov_btn.setMinimumSize(QtCore.QSize(150, 25))
        self.load_mov_btn.setMaximumSize(QtCore.QSize(150, 25))
        self.load_mov_btn.setBaseSize(QtCore.QSize(25, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_mov_btn.setFont(font)
        self.load_mov_btn.setObjectName("load_mov_btn")
        self.load_layout.addWidget(self.load_mov_btn, 2, 0, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.load_layout)
        self.fit_chk_boxes = QtWidgets.QGridLayout()
        self.fit_chk_boxes.setObjectName("fit_chk_boxes")
        self.checkBox561 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox561.setMinimumSize(QtCore.QSize(45, 10))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(9)
        self.checkBox561.setFont(font)
        self.checkBox561.setStyleSheet("QCheckBox { color: rgb(255, 255, 0); text-decoration: underline;font: 75 10pt \"MS Shell Dlg 2\";}")
        self.checkBox561.setObjectName("checkBox561")
        self.fit_chk_boxes.addWidget(self.checkBox561, 0, 3, 1, 1)
        self.checkBox647 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox647.setMinimumSize(QtCore.QSize(45, 10))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(9)
        self.checkBox647.setFont(font)
        self.checkBox647.setStyleSheet("QCheckBox { color: rgb(255, 85, 0); text-decoration: underline;font: 75 10pt \"MS Shell Dlg 2\";}")
        self.checkBox647.setObjectName("checkBox647")
        self.fit_chk_boxes.addWidget(self.checkBox647, 0, 2, 1, 1)
        self.checkBox488 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox488.setMinimumSize(QtCore.QSize(45, 10))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(9)
        self.checkBox488.setFont(font)
        self.checkBox488.setStyleSheet("QCheckBox { color: rgb(0, 255, 255); text-decoration: underline;font: 75 10pt \"MS Shell Dlg 2\";}")
        self.checkBox488.setObjectName("checkBox488")
        self.fit_chk_boxes.addWidget(self.checkBox488, 0, 4, 1, 1)
        self.chl_lbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chl_lbl.sizePolicy().hasHeightForWidth())
        self.chl_lbl.setSizePolicy(sizePolicy)
        self.chl_lbl.setMinimumSize(QtCore.QSize(150, 20))
        self.chl_lbl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.chl_lbl.setBaseSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chl_lbl.setFont(font)
        self.chl_lbl.setObjectName("chl_lbl")
        self.fit_chk_boxes.addWidget(self.chl_lbl, 0, 0, 1, 1)
        self.checkBox750 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox750.setMinimumSize(QtCore.QSize(45, 10))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(9)
        self.checkBox750.setFont(font)
        self.checkBox750.setStyleSheet("QCheckBox { color: red; text-decoration: underline; \n"
"    font: 75 10pt \"MS Shell Dlg 2\"; }")
        self.checkBox750.setObjectName("checkBox750")
        self.fit_chk_boxes.addWidget(self.checkBox750, 0, 1, 1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.fit_chk_boxes)
        self.align_chk_boxes = QtWidgets.QGridLayout()
        self.align_chk_boxes.setObjectName("align_chk_boxes")
        self.align_chl_lbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.align_chl_lbl.sizePolicy().hasHeightForWidth())
        self.align_chl_lbl.setSizePolicy(sizePolicy)
        self.align_chl_lbl.setMinimumSize(QtCore.QSize(150, 20))
        self.align_chl_lbl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.align_chl_lbl.setBaseSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.align_chl_lbl.setFont(font)
        self.align_chl_lbl.setObjectName("align_chl_lbl")
        self.align_chk_boxes.addWidget(self.align_chl_lbl, 0, 0, 1, 1)
        self.a_checkBox561 = QtWidgets.QCheckBox(self.centralwidget)
        self.a_checkBox561.setMinimumSize(QtCore.QSize(45, 10))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(9)
        self.a_checkBox561.setFont(font)
        self.a_checkBox561.setStyleSheet("QCheckBox { color: yellow; text-decoration: underline;font: 75 8pt \"MS Shell Dlg 2\";}")
        self.a_checkBox561.setObjectName("a_checkBox561")
        self.align_chk_boxes.addWidget(self.a_checkBox561, 0, 1, 1, 1)
        self.a_checkBox488 = QtWidgets.QCheckBox(self.centralwidget)
        self.a_checkBox488.setMinimumSize(QtCore.QSize(45, 10))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(9)
        self.a_checkBox488.setFont(font)
        self.a_checkBox488.setStyleSheet("QCheckBox { color: cyan; text-decoration: underline;font: 75 8pt \"MS Shell Dlg 2\";}")
        self.a_checkBox488.setObjectName("a_checkBox488")
        self.align_chk_boxes.addWidget(self.a_checkBox488, 0, 2, 1, 1)
        
        self.proc_lbl = QtWidgets.QLabel(self.centralwidget)
        self.proc_lbl.setMinimumSize(QtCore.QSize(150, 20))
        self.proc_lbl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.proc_lbl.setBaseSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.proc_lbl.setFont(font)
        self.proc_lbl.setObjectName("fit_proc_lbl")
        self.align_chk_boxes.addWidget(self.proc_lbl, 4, 0, 1, 1)
        self.proc_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.proc_spin_box.setFont(font)
        self.proc_spin_box.setObjectName("proc_spin_box")
        self.proc_spin_box.setMaximum(1000)
        self.align_chk_boxes.addWidget(self.proc_spin_box, 4, 1, 1, 1)
        self.proc_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proc_slider.sizePolicy().hasHeightForWidth())
        self.proc_slider.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.proc_slider.setFont(font)
        self.proc_slider.setOrientation(QtCore.Qt.Horizontal)
        self.proc_slider.setObjectName("proc_slider")
        self.align_chk_boxes.addWidget(self.proc_slider, 5, 0, 1, 1)
        
        
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.align_chk_boxes)
        
        
        self.analysis_layout = QtWidgets.QGridLayout()
        self.analysis_layout.setObjectName("analysis_layout")
        self.fit_title_lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.fit_title_lbl.setFont(font)
        self.fit_title_lbl.setObjectName("fit_title_lbl")
        self.analysis_layout.addWidget(self.fit_title_lbl, 0, 0, 1, 2)
        self.test_params_btn = QtWidgets.QPushButton(self.centralwidget)
        self.test_params_btn.setMinimumSize(QtCore.QSize(150, 25))
        self.test_params_btn.setMaximumSize(QtCore.QSize(150, 25))
        self.test_params_btn.setBaseSize(QtCore.QSize(25, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.test_params_btn.setFont(font)
        self.test_params_btn.setObjectName("test_params_btn")
        self.analysis_layout.addWidget(self.test_params_btn, 1, 0, 1, 1)
        self.load_loc1_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_loc1_btn.setMinimumSize(QtCore.QSize(150, 25))
        self.load_loc1_btn.setMaximumSize(QtCore.QSize(150, 25))
        self.load_loc1_btn.setBaseSize(QtCore.QSize(25, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_loc1_btn.setFont(font)
        self.load_loc1_btn.setObjectName("load_loc1_btn")
        self.analysis_layout.addWidget(self.load_loc1_btn, 2, 0, 1, 1)
        self.load_loc2_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_loc2_btn.setMinimumSize(QtCore.QSize(150, 25))
        self.load_loc2_btn.setMaximumSize(QtCore.QSize(150, 25))
        self.load_loc2_btn.setBaseSize(QtCore.QSize(25, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_loc2_btn.setFont(font)
        self.load_loc2_btn.setObjectName("load_loc2_btn")
        self.analysis_layout.addWidget(self.load_loc2_btn, 2, 1, 1, 1)
        
        self.fit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.fit_btn.setMinimumSize(QtCore.QSize(150, 25))
        self.fit_btn.setMaximumSize(QtCore.QSize(150, 25))
        self.fit_btn.setBaseSize(QtCore.QSize(25, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fit_btn.setFont(font)
        self.fit_btn.setObjectName("fit_btn")
        self.analysis_layout.addWidget(self.fit_btn, 3, 0, 1, 1)

        self.fit_frame_lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fit_frame_lbl.setFont(font)
        self.fit_frame_lbl.setObjectName("fit_frame_lbl")
        self.analysis_layout.addWidget(self.fit_frame_lbl, 4, 0, 1, 1)
            
        self.fit_frame_select = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fit_frame_select.setFont(font)
        self.fit_frame_select.setObjectName("fit_frame_select")
        self.fit_frame_select.setMinimum(-1)
        self.fit_frame_select.setMaximum(1000)
        self.analysis_layout.addWidget(self.fit_frame_select, 4, 1, 1, 1)
    
        self.scmos_title_lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.scmos_title_lbl.setFont(font)
        self.scmos_title_lbl.setObjectName("scmos_title_lbl")
        self.analysis_layout.addWidget(self.scmos_title_lbl, 6, 0, 1, 1)
        self.frame_rg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.frame_rg_btn.setMinimumSize(QtCore.QSize(150, 25))
        self.frame_rg_btn.setMaximumSize(QtCore.QSize(150, 25))
        self.frame_rg_btn.setBaseSize(QtCore.QSize(25, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_rg_btn.setFont(font)
        self.frame_rg_btn.setObjectName("frame_rg_btn")
        self.analysis_layout.addWidget(self.frame_rg_btn, 7, 0, 1, 1)
        self.multifit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.multifit_btn.setMinimumSize(QtCore.QSize(150, 25))
        self.multifit_btn.setMaximumSize(QtCore.QSize(150, 25))
        self.multifit_btn.setBaseSize(QtCore.QSize(25, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.multifit_btn.setFont(font)
        self.multifit_btn.setObjectName("multifit_btn")
        self.analysis_layout.addWidget(self.multifit_btn, 8, 0, 1, 1)
               
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.analysis_layout)
        self.horizontalLayout_5.addLayout(self.formLayout)
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setBaseSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mdiArea.setFont(font)
        self.mdiArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mdiArea.setAutoFillBackground(True)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow = QtWidgets.QWidget()
        self.subwindow.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subwindow.sizePolicy().hasHeightForWidth())
        self.subwindow.setSizePolicy(sizePolicy)
        self.subwindow.setMinimumSize(QtCore.QSize(800, 400))
        self.subwindow.setBaseSize(QtCore.QSize(0, 0))
        self.subwindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.subwindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.subwindow.setObjectName("subwindow")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.subwindow)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mov_path_lbl = QtWidgets.QLabel(self.subwindow)
        self.mov_path_lbl.setObjectName("mov_path_lbl")
        self.gridLayout_6.addWidget(self.mov_path_lbl, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nmPerPixLabel = QtWidgets.QLabel(self.subwindow)
        self.nmPerPixLabel.setObjectName("nmPerPixLabel")
        self.horizontalLayout.addWidget(self.nmPerPixLabel)
        self.nmPerPixelSpinBox = QtWidgets.QDoubleSpinBox(self.subwindow)
        self.nmPerPixelSpinBox.setMaximum(1000.0)
        self.nmPerPixelSpinBox.setProperty("value", 160.0)
        self.nmPerPixelSpinBox.setObjectName("nmPerPixelSpinBox")
        self.horizontalLayout.addWidget(self.nmPerPixelSpinBox)
        self.frame_lbl = QtWidgets.QLabel(self.subwindow)
        self.frame_lbl.setObjectName("frame_lbl")
        self.horizontalLayout.addWidget(self.frame_lbl)
        self.frame_spin_box = QtWidgets.QDoubleSpinBox(self.subwindow)
        self.frame_spin_box.setMaximum(10000.0)
        self.frame_spin_box.setProperty("value", 160.0)
        self.frame_spin_box.setObjectName("frame_spin_box")
        self.horizontalLayout.addWidget(self.frame_spin_box)
        self.nmPerPixLabel_2 = QtWidgets.QLabel(self.subwindow)
        self.nmPerPixLabel_2.setObjectName("nmPerPixLabel_2")
        self.horizontalLayout.addWidget(self.nmPerPixLabel_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.xyiLabel = QtWidgets.QLabel(self.subwindow)
        self.xyiLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.xyiLabel.setMaximumSize(QtCore.QSize(0, 16777215))
        self.xyiLabel.setScaledContents(False)
        self.xyiLabel.setObjectName("xyiLabel")
        self.horizontalLayout.addWidget(self.xyiLabel)
        self.fileLabel = QtWidgets.QLabel(self.subwindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileLabel.sizePolicy().hasHeightForWidth())
        self.fileLabel.setSizePolicy(sizePolicy)
        self.fileLabel.setMinimumSize(QtCore.QSize(300, 0))
        self.fileLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setKerning(False)
        self.fileLabel.setFont(font)
        self.fileLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fileLabel.setObjectName("fileLabel")
        self.horizontalLayout.addWidget(self.fileLabel)
        self.gridLayout_6.addLayout(self.horizontalLayout, 2, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(self.subwindow)
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.locs1Label = QtWidgets.QLabel(self.groupBox)
        self.locs1Label.setObjectName("locs1Label")
        self.verticalLayout_12.addWidget(self.locs1Label)
        self.locs1TableWidget = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locs1TableWidget.sizePolicy().hasHeightForWidth())
        self.locs1TableWidget.setSizePolicy(sizePolicy)
        self.locs1TableWidget.setMaximumSize(QtCore.QSize(16777215, 210))
        self.locs1TableWidget.setShowGrid(True)
        self.locs1TableWidget.setObjectName("locs1TableWidget")
        self.locs1TableWidget.setColumnCount(0)
        self.locs1TableWidget.setRowCount(0)
        self.locs1TableWidget.horizontalHeader().setVisible(False)
        self.locs1TableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.locs1TableWidget.horizontalHeader().setStretchLastSection(True)
        self.locs1TableWidget.verticalHeader().setVisible(False)
        self.locs1TableWidget.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout_12.addWidget(self.locs1TableWidget)
        self.locs2Label = QtWidgets.QLabel(self.groupBox)
        self.locs2Label.setObjectName("locs2Label")
        self.verticalLayout_12.addWidget(self.locs2Label)
        self.locs2TableWidget = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locs2TableWidget.sizePolicy().hasHeightForWidth())
        self.locs2TableWidget.setSizePolicy(sizePolicy)
        self.locs2TableWidget.setShowGrid(True)
        self.locs2TableWidget.setObjectName("locs2TableWidget")
        self.locs2TableWidget.setColumnCount(0)
        self.locs2TableWidget.setRowCount(0)
        self.locs2TableWidget.horizontalHeader().setVisible(False)
        self.locs2TableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.locs2TableWidget.horizontalHeader().setStretchLastSection(True)
        self.locs2TableWidget.verticalHeader().setVisible(False)
        self.locs2TableWidget.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout_12.addWidget(self.locs2TableWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.gridLayout_6.addWidget(self.groupBox, 1, 2, 1, 1)
        self.movieGroupBox = QtWidgets.QGroupBox(self.subwindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movieGroupBox.sizePolicy().hasHeightForWidth())
        self.movieGroupBox.setSizePolicy(sizePolicy)
        self.movieGroupBox.setObjectName("movieGroupBox")
        self.gridLayout_6.addWidget(self.movieGroupBox, 1, 0, 1, 1)
        self.rangeGroupBox = QtWidgets.QGroupBox(self.subwindow)
        self.rangeGroupBox.setObjectName("rangeGroupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.rangeGroupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.maxSpinBox = QtWidgets.QSpinBox(self.rangeGroupBox)
        self.maxSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.maxSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.maxSpinBox.setMaximum(100000)
        self.maxSpinBox.setProperty("value", 1000)
        self.maxSpinBox.setObjectName("maxSpinBox")
        self.verticalLayout_11.addWidget(self.maxSpinBox)
        self.rangeSliderWidget = QtWidgets.QWidget(self.rangeGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeSliderWidget.sizePolicy().hasHeightForWidth())
        self.rangeSliderWidget.setSizePolicy(sizePolicy)
        self.rangeSliderWidget.setMinimumSize(QtCore.QSize(45, 0))
        self.rangeSliderWidget.setMaximumSize(QtCore.QSize(45, 16777215))
        self.rangeSliderWidget.setObjectName("rangeSliderWidget")
        self.verticalLayout_11.addWidget(self.rangeSliderWidget)
        self.minSpinBox = QtWidgets.QSpinBox(self.rangeGroupBox)
        self.minSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.minSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.minSpinBox.setMaximum(100000)
        self.minSpinBox.setProperty("value", 100)
        self.minSpinBox.setObjectName("minSpinBox")
        self.verticalLayout_11.addWidget(self.minSpinBox)
        self.gridLayout_6.addWidget(self.rangeGroupBox, 1, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.mdiArea)
        self.mdiArea.addSubWindow(self.subwindow)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Movie = QtWidgets.QAction(MainWindow)
        self.actionLoad_Movie.setObjectName("actionLoad_Movie")
        self.actionLoad_Locs1 = QtWidgets.QAction(MainWindow)
        self.actionLoad_Locs1.setObjectName("actionLoad_Locs1")
        self.actionLoad_Locs2 = QtWidgets.QAction(MainWindow)
        self.actionLoad_Locs2.setObjectName("actionLoad_Locs2")
        self.actionCapture = QtWidgets.QAction(MainWindow)
        self.actionCapture.setObjectName("actionCapture")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLoad_Experiment_Folder = QtWidgets.QAction(MainWindow)
        self.actionLoad_Experiment_Folder.setObjectName("actionLoad_Experiment_Folder")
        self.actionLoad_Training_Parameters = QtWidgets.QAction(MainWindow)
        self.actionLoad_Training_Parameters.setObjectName("actionLoad_Training_Parameters")
        self.menuFile.addAction(self.actionLoad_Experiment_Folder)
        self.menuFile.addAction(self.actionLoad_Training_Parameters)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Movie)
        self.menuFile.addAction(self.actionLoad_Locs1)
        self.menuFile.addAction(self.actionLoad_Locs2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCapture)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Analysis "))
        self.exp_lbl.setText(_translate("MainWindow", "NA"))
        self.load_exp_btn.setText(_translate("MainWindow", "Load Experiment Folder"))
        self.load_mov_btn.setText(_translate("MainWindow", "Load Movie"))
        self.checkBox561.setText(_translate("MainWindow", "561"))
        self.checkBox647.setText(_translate("MainWindow", "647"))
        self.checkBox488.setText(_translate("MainWindow", "488"))
        self.chl_lbl.setText(_translate("MainWindow", "STORM Channels"))
        self.checkBox750.setText(_translate("MainWindow", "750"))
        self.align_chl_lbl.setText(_translate("MainWindow", "Alignment Channels"))
        self.a_checkBox561.setText(_translate("MainWindow", "561"))
        self.a_checkBox488.setText(_translate("MainWindow", "488"))
        self.fit_title_lbl.setText(_translate("MainWindow", "Fitting Parameters Evaluation"))
        self.test_params_btn.setText(_translate("MainWindow", "Set Test Parameters"))
        self.load_loc1_btn.setText(_translate("MainWindow", "Load Localization 1"))
        self.load_loc2_btn.setText(_translate("MainWindow", "Load Localization 2"))
        self.fit_btn.setText(_translate("MainWindow", "Fit Parameters"))
        self.fit_frame_lbl.setText(_translate("MainWindow", "Movie for Fitting Evaluation"))
        self.proc_lbl.setText(_translate("MainWindow", "Number of Processes"))
        self.scmos_title_lbl.setText(_translate("MainWindow", "sCMOS Analysis"))
        self.frame_rg_btn.setText(_translate("MainWindow", "Set Frame Range"))
        self.multifit_btn.setText(_translate("MainWindow", "Multifit Analysis"))
        self.subwindow.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.subwindow.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.mov_path_lbl.setText(_translate("MainWindow", "Movie:"))
        self.nmPerPixLabel.setText(_translate("MainWindow", "nm per pixel:"))
        self.frame_lbl.setText(_translate("MainWindow", "Frame"))
        self.nmPerPixLabel_2.setText(_translate("MainWindow", "of 10000"))
        self.xyiLabel.setText(_translate("MainWindow", "NA"))
        self.fileLabel.setText(_translate("MainWindow", "NA"))
        self.groupBox.setTitle(_translate("MainWindow", "Localization Fit Parameters"))
        self.locs1Label.setText(_translate("MainWindow", "Localizations 1 Results"))
        self.locs2Label.setText(_translate("MainWindow", "Localizations 2 Results"))
        self.movieGroupBox.setTitle(_translate("MainWindow", "Movie"))
        self.rangeGroupBox.setTitle(_translate("MainWindow", "Contrast"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Movie.setText(_translate("MainWindow", "Load Movie"))
        self.actionLoad_Locs1.setText(_translate("MainWindow", "Load Localizations 1"))
        self.actionLoad_Locs2.setText(_translate("MainWindow", "Load Localizations 2"))
        self.actionCapture.setText(_translate("MainWindow", "Frame Capture"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionLoad_Experiment_Folder.setText(_translate("MainWindow", "Load Experiment Folder"))
        self.actionLoad_Training_Parameters.setText(_translate("MainWindow", "Load Training Parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
