# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_parameters_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(488, 242)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sf = QtWidgets.QSpinBox(Dialog)
        self.sf.setObjectName("sf")
        self.sf.setMaximum(100000)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sf)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ef = QtWidgets.QSpinBox(Dialog)
        self.ef.setObjectName("ef")
        self.ef.setMaximum(100000)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ef)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{color: rgb(170, 0, 0)}")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.thresh750 = QtWidgets.QDoubleSpinBox(Dialog)
        self.thresh750.setObjectName("thresh750")
        self.gridLayout.addWidget(self.thresh750, 0, 2, 1, 1)
        self.find750 = QtWidgets.QPushButton(Dialog)
        self.find750.setObjectName("find750")
        self.gridLayout.addWidget(self.find750, 0, 3, 1, 1)
        self.pathLbl750 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLbl750.sizePolicy().hasHeightForWidth())
        self.pathLbl750.setSizePolicy(sizePolicy)
        self.pathLbl750.setMinimumSize(QtCore.QSize(200, 10))
        self.pathLbl750.setStyleSheet("QLabel{background-color: \'gray\'} ")
        self.pathLbl750.setText("")
        self.pathLbl750.setObjectName("pathLbl750")
        self.gridLayout.addWidget(self.pathLbl750, 0, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel{color: rgb(255,85, 0)}")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.thresh647 = QtWidgets.QDoubleSpinBox(Dialog)
        self.thresh647.setObjectName("thresh647")
        self.gridLayout.addWidget(self.thresh647, 1, 2, 1, 1)
        self.find647 = QtWidgets.QPushButton(Dialog)
        self.find647.setObjectName("find647")
        self.gridLayout.addWidget(self.find647, 1, 3, 1, 1)
        self.pathLbl647 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLbl647.sizePolicy().hasHeightForWidth())
        self.pathLbl647.setSizePolicy(sizePolicy)
        self.pathLbl647.setMinimumSize(QtCore.QSize(200, 10))
        self.pathLbl647.setStyleSheet("QLabel{background-color: \'gray\'} ")
        self.pathLbl647.setText("")
        self.pathLbl647.setObjectName("pathLbl647")
        self.gridLayout.addWidget(self.pathLbl647, 1, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel{color: rgb(255, 255, 0)}")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.thresh561 = QtWidgets.QDoubleSpinBox(Dialog)
        self.thresh561.setObjectName("thresh561")
        self.gridLayout.addWidget(self.thresh561, 2, 2, 1, 1)
        self.find561 = QtWidgets.QPushButton(Dialog)
        self.find561.setObjectName("find561")
        self.gridLayout.addWidget(self.find561, 2, 3, 1, 1)
        self.pathLbl561 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLbl561.sizePolicy().hasHeightForWidth())
        self.pathLbl561.setSizePolicy(sizePolicy)
        self.pathLbl561.setMinimumSize(QtCore.QSize(200, 10))
        self.pathLbl561.setStyleSheet("QLabel{background-color: \'gray\'} ")
        self.pathLbl561.setText("")
        self.pathLbl561.setObjectName("pathLbl561")
        self.gridLayout.addWidget(self.pathLbl561, 2, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{color: \'cyan\'}")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.thresh488 = QtWidgets.QDoubleSpinBox(Dialog)
        self.thresh488.setObjectName("thresh488")
        self.gridLayout.addWidget(self.thresh488, 3, 2, 1, 1)
        self.find488 = QtWidgets.QPushButton(Dialog)
        self.find488.setObjectName("find488")
        self.gridLayout.addWidget(self.find488, 3, 3, 1, 1)
        self.pathLbl488 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLbl488.sizePolicy().hasHeightForWidth())
        self.pathLbl488.setSizePolicy(sizePolicy)
        self.pathLbl488.setMinimumSize(QtCore.QSize(200, 10))
        self.pathLbl488.setStyleSheet("QLabel{background-color: \'gray\'} ")
        self.pathLbl488.setText("")
        self.pathLbl488.setObjectName("pathLbl488")
        self.gridLayout.addWidget(self.pathLbl488, 3, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.advancedBtn = QtWidgets.QPushButton(Dialog)
        self.advancedBtn.setStyleSheet("QPushButton{background-color: \'gray\'}")
        self.advancedBtn.setObjectName("advancedBtn")
        self.gridLayout_2.addWidget(self.advancedBtn, 3, 1, 1, 1)
        self.updateBtn = QtWidgets.QPushButton(Dialog)
        self.updateBtn.setObjectName("updateBtn")
        self.gridLayout_2.addWidget(self.updateBtn, 2, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Input Parameters"))
        self.label.setText(_translate("Dialog", "Start Frame"))
        self.label_2.setText(_translate("Dialog", "End Frame"))
        self.label_9.setText(_translate("Dialog", "750"))
        self.label_8.setText(_translate("Dialog", "Threshold"))
        self.find750.setText(_translate("Dialog", "Find XML"))
        self.label_10.setText(_translate("Dialog", "647"))
        self.label_5.setText(_translate("Dialog", "Threshold"))
        self.find647.setText(_translate("Dialog", "Find XML"))
        self.label_11.setText(_translate("Dialog", "561"))
        self.label_7.setText(_translate("Dialog", "Threshold"))
        self.find561.setText(_translate("Dialog", "Find XML"))
        self.label_12.setText(_translate("Dialog", "488"))
        self.label_6.setText(_translate("Dialog", "Threshold"))
        self.find488.setText(_translate("Dialog", "Find XML"))
        self.advancedBtn.setText(_translate("Dialog", "Advanced"))
        self.updateBtn.setText(_translate("Dialog", "Update XMLs"))

def main(): 
    ui = Ui_Dialog()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

